# Generated by Django 5.2.6 on 2025-09-20 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(help_text='來源（如 Google Places）的唯一識別碼', max_length=300, unique=True, verbose_name='Place ID')),
                ('name', models.CharField(max_length=200, verbose_name='餐廳名稱')),
                ('formatted_address', models.CharField(blank=True, max_length=400, verbose_name='完整地址')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('business_status', models.CharField(choices=[('OPERATIONAL', '營業中（官方狀態）'), ('CLOSED_TEMPORARILY', '暫時停業（官方狀態）'), ('CLOSED_PERMANENTLY', '永久停業（官方狀態）')], default='OPERATIONAL', max_length=30, verbose_name='官方營運狀態')),
                ('open_status', models.CharField(choices=[('open', '營業中'), ('closed', '已打烊'), ('unknown', '未知')], default='unknown', help_text='open=營業中 / closed=已打烊 / unknown=未知', max_length=10, verbose_name='當前營業狀態')),
                ('current_open_now', models.BooleanField(blank=True, null=True, verbose_name='來源判斷：現在是否營業')),
                ('open_until', models.DateTimeField(blank=True, null=True, verbose_name='本次營業至（預估）')),
                ('reopen_at', models.DateTimeField(blank=True, null=True, verbose_name='下次開門（預估）')),
                ('price_level', models.PositiveSmallIntegerField(blank=True, choices=[(0, '免費 / 未定價'), (1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], null=True, verbose_name='價位等級')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='平均評分')),
                ('user_ratings_total', models.IntegerField(blank=True, null=True, verbose_name='評分數量')),
                ('types', models.JSONField(blank=True, null=True, verbose_name='類別清單')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='電話（本地格式）')),
                ('intl_phone', models.CharField(blank=True, max_length=40, verbose_name='電話（國際格式）')),
                ('website', models.URLField(blank=True, verbose_name='官方網站')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google 地圖連結')),
                ('weekday_text', models.JSONField(blank=True, null=True, verbose_name='每週營業時間（文字）')),
                ('time_zone', models.CharField(blank=True, max_length=64, verbose_name='時區（IANA）')),
                ('utc_offset_minutes', models.IntegerField(blank=True, null=True, verbose_name='UTC 位移（分鐘）')),
                ('editorial_summary', models.TextField(blank=True, verbose_name='官方/編輯摘要')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('primary_source', models.CharField(choices=[('places_details', 'Google Places Details'), ('places_textsearch', 'Google Places Text Search'), ('gmaps_scrape', 'Google Maps 抓取'), ('ifoodie', '愛食記'), ('gmap_photo', 'Google Photo API'), ('manual', '手動')], default='places_details', max_length=32, verbose_name='主要來源')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='資料語系')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次寫入時間')),
                ('last_fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近抓取時間')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='來源原始 JSON')),
            ],
            options={
                'verbose_name': '餐廳',
                'verbose_name_plural': '餐廳',
                'indexes': [models.Index(fields=['name'], name='restaurants_name_0080ba_idx'), models.Index(fields=['lat', 'lng'], name='restaurants_lat_766c3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, verbose_name='屬性鍵')),
                ('value', models.CharField(blank=True, max_length=120, verbose_name='屬性值')),
                ('source', models.CharField(choices=[('places_details', 'Google Places Details'), ('places_textsearch', 'Google Places Text Search'), ('gmaps_scrape', 'Google Maps 抓取'), ('ifoodie', '愛食記'), ('gmap_photo', 'Google Photo API'), ('manual', '手動')], default='manual', max_length=32, verbose_name='來源')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '餐廳屬性',
                'verbose_name_plural': '餐廳屬性',
                'unique_together': {('restaurant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantOpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '週一'), (1, '週二'), (2, '週三'), (3, '週四'), (4, '週五'), (5, '週六'), (6, '週日')], verbose_name='星期')),
                ('open_time', models.TimeField(verbose_name='開門時間')),
                ('close_time', models.TimeField(verbose_name='打烊時間')),
                ('crosses_midnight', models.BooleanField(default=False, verbose_name='是否跨日')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '營業時間（每週）',
                'verbose_name_plural': '營業時間（每週）',
                'indexes': [models.Index(fields=['restaurant', 'weekday'], name='restaurants_restaur_a64075_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('places_details', 'Google Places Details'), ('places_textsearch', 'Google Places Text Search'), ('gmaps_scrape', 'Google Maps 抓取'), ('ifoodie', '愛食記'), ('gmap_photo', 'Google Photo API'), ('manual', '手動')], default='gmap_photo', max_length=32, verbose_name='來源')),
                ('photo_reference', models.CharField(blank=True, max_length=500, verbose_name='Photo Reference')),
                ('remote_url', models.URLField(blank=True, verbose_name='遠端圖片 URL')),
                ('file', models.ImageField(blank=True, upload_to='restaurant_photos', verbose_name='本地圖片檔')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='寬度')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高度')),
                ('attribution', models.TextField(blank=True, verbose_name='版權/出處標示')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='蒐集時間')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '餐廳圖片',
                'verbose_name_plural': '餐廳圖片',
                'indexes': [models.Index(fields=['restaurant'], name='restaurants_restaur_6aa341_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('places_details', 'Google Places Details'), ('places_textsearch', 'Google Places Text Search'), ('gmaps_scrape', 'Google Maps 抓取'), ('ifoodie', '愛食記'), ('gmap_photo', 'Google Photo API'), ('manual', '手動')], default='places_details', max_length=32, verbose_name='來源')),
                ('author_name', models.CharField(blank=True, max_length=120, verbose_name='作者名稱')),
                ('author_url', models.URLField(blank=True, verbose_name='作者連結')),
                ('profile_photo_url', models.URLField(blank=True, verbose_name='作者頭像')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='評分（1-5）')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='語系')),
                ('text', models.TextField(blank=True, verbose_name='評論內容')),
                ('time_unix', models.BigIntegerField(blank=True, null=True, verbose_name='評論時間（UNIX）')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='評論時間（轉換後）')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='原始 JSON')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '餐廳評論',
                'verbose_name_plural': '餐廳評論',
                'indexes': [models.Index(fields=['restaurant', 'rating'], name='restaurants_restaur_17b914_idx'), models.Index(fields=['restaurant', 'published_at'], name='restaurants_restaur_541dc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSourceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('places_details', 'Google Places Details'), ('places_textsearch', 'Google Places Text Search'), ('gmaps_scrape', 'Google Maps 抓取'), ('ifoodie', '愛食記'), ('gmap_photo', 'Google Photo API'), ('manual', '手動')], max_length=32, verbose_name='來源')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='抓取時間')),
                ('status_code', models.CharField(blank=True, max_length=20, verbose_name='來源回應碼')),
                ('etag', models.CharField(blank=True, max_length=80, verbose_name='ETag/版本')),
                ('quota_cost', models.IntegerField(blank=True, null=True, verbose_name='配額消耗')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='原始 JSON')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_meta', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '來源追蹤',
                'verbose_name_plural': '來源追蹤',
                'indexes': [models.Index(fields=['restaurant', 'source', 'fetched_at'], name='restaurants_restaur_1f0af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSpecialHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('is_open', models.BooleanField(default=True, verbose_name='是否營業')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='開門時間')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='打烊時間')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '特殊營業時間',
                'verbose_name_plural': '特殊營業時間',
                'indexes': [models.Index(fields=['restaurant', 'date'], name='restaurants_restaur_bb0f0a_idx')],
            },
        ),
    ]
