# Generated by Django 5.2.6 on 2025-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dining_date',
            field=models.DateField(blank=True, help_text='用餐日期', null=True),
        ),
    ]
