# Generated by Django 5.2.6 on 2025-09-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
