# Generated by Django 4.2.24 on 2025-09-17 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', help_text='偏好，例如「甜」「辣」「不吃牛」', max_length=50)),
                ('preference_type', models.CharField(choices=[('like', '喜歡'), ('dislike', '不喜歡')], default='like', max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('frequency', models.IntegerField(default=1)),
                ('source', models.CharField(choices=[('dialog', '對話'), ('profile', '使用者設定'), ('history', '點餐紀錄')], default='dialog', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
                'unique_together': {('user', 'keyword', 'preference_type')},
            },
        ),
    ]
