# Generated by Django 5.2.6 on 2025-09-20 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內容')),
                ('announcement_type', models.CharField(choices=[('system', '系統公告'), ('maintenance', '系統維護'), ('update', '功能更新'), ('promotion', '活動宣傳'), ('other', '其他')], default='system', max_length=15, verbose_name='公告類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置頂')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始日期')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束日期')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'verbose_name': '系統公告',
                'verbose_name_plural': '系統公告',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, verbose_name='商家名稱')),
                ('business_registration_number', models.CharField(max_length=50, verbose_name='統一編號/營業登記字號')),
                ('business_address', models.CharField(max_length=200, verbose_name='商家地址')),
                ('business_phone', models.CharField(max_length=20, verbose_name='商家電話')),
                ('business_email', models.EmailField(max_length=254, verbose_name='商家 Email')),
                ('registration_document', models.FileField(upload_to='verification_documents', verbose_name='證明文件')),
                ('additional_notes', models.TextField(blank=True, verbose_name='補充說明')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('status', models.CharField(choices=[('unverified', '未驗證'), ('pending', '審核中'), ('verified', '已驗證'), ('rejected', '已拒絕')], default='pending', max_length=10, verbose_name='審核狀態')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('review_notes', models.TextField(blank=True, verbose_name='審核意見')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='審核者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'verbose_name': '商家驗證申請',
                'verbose_name_plural': '商家驗證申請',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='user.comment', verbose_name='回覆對象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='圖片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('is_pinned', models.BooleanField(default=False, help_text='是否將貼文置頂於個人頁面', verbose_name='是否置頂')),
                ('is_platform_featured', models.BooleanField(default=False, help_text='是否為平台推薦貼文', verbose_name='平台推薦')),
                ('location_name', models.CharField(blank=True, help_text='餐廳名稱或地點名稱', max_length=200, null=True, verbose_name='地點名稱')),
                ('location_address', models.CharField(blank=True, help_text='餐廳地址', max_length=300, null=True, verbose_name='地點地址')),
                ('location_lat', models.FloatField(blank=True, help_text='地點緯度', null=True, verbose_name='緯度')),
                ('location_lng', models.FloatField(blank=True, help_text='地點經度', null=True, verbose_name='經度')),
                ('location_place_id', models.CharField(blank=True, help_text='Google Places ID', max_length=300, null=True, verbose_name='Place ID')),
                ('restaurant', models.ForeignKey(blank=True, help_text='可留空；後端會依 Place ID 自動對應/建立', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant', verbose_name='關聯餐廳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '貼文',
                'verbose_name_plural': '貼文',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', '評論'), ('reply', '回覆'), ('follow', '追蹤'), ('favorite', '收藏'), ('reaction', '表情符號'), ('system', '系統通知')], max_length=10, verbose_name='通知類型')),
                ('message', models.TextField(verbose_name='通知內容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.comment', verbose_name='關聯留言')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='發送者')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.post', verbose_name='關聯貼文')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.post', verbose_name='貼文'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='頭像')),
                ('bio', models.TextField(blank=True, verbose_name='自介')),
                ('favorite_foods', models.CharField(blank=True, help_text='請列出您喜愛的食物，用逗號分隔', max_length=200, verbose_name='喜愛食物')),
                ('food_restrictions', models.CharField(blank=True, help_text='請列出您的飲食禁忌，用逗號分隔', max_length=200, verbose_name='飲食禁忌')),
                ('user_type', models.CharField(choices=[('general', '一般使用者'), ('business', '商家'), ('admin', '管理員')], default='general', max_length=10, verbose_name='使用者類型')),
                ('verification_status', models.CharField(choices=[('unverified', '未驗證'), ('pending', '審核中'), ('verified', '已驗證'), ('rejected', '已拒絕')], default='unverified', max_length=10, verbose_name='驗證狀態')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='商家名稱')),
                ('business_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='商家地址')),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='商家電話')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帳號')),
            ],
            options={
                'verbose_name': '個人資料',
                'verbose_name_plural': '個人資料',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('post', '貼文'), ('comment', '評論'), ('user', '用戶'), ('other', '其他')], max_length=10, verbose_name='回報類型')),
                ('reason', models.TextField(verbose_name='回報原因')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('resolved', '已解決'), ('rejected', '已拒絕')], default='pending', max_length=10, verbose_name='處理狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='處理時間')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理備註')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.comment', verbose_name='被回報留言')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL, verbose_name='處理者')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.post', verbose_name='被回報貼文')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='被回報用戶')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL, verbose_name='檢舉者')),
            ],
            options={
                'verbose_name': '回報',
                'verbose_name_plural': '回報',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='restaurants.restaurant', verbose_name='餐廳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '收藏餐廳',
                'verbose_name_plural': '收藏餐廳',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='被追蹤者')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='追蹤者')),
            ],
            options={
                'verbose_name': '追蹤關係',
                'verbose_name_plural': '追蹤關係',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='user.post', verbose_name='貼文')),
            ],
            options={
                'verbose_name': '收藏貼文',
                'verbose_name_plural': '收藏貼文',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍 讚'), ('love', '❤️ 愛心'), ('haha', '😄 哈哈'), ('wow', '😲 哇'), ('sad', '😢 傷心'), ('angry', '😠 怒')], max_length=10, verbose_name='反應類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='user.post', verbose_name='貼文')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '互動反應',
                'verbose_name_plural': '互動反應',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
