# Generated by Django 4.2.20 on 2025-05-31 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_address', models.CharField(blank=True, max_length=300, null=True)),
                ('restaurant_image_url', models.URLField(blank=True, null=True)),
                ('restaurant_place_id', models.CharField(blank=True, max_length=300, null=True)),
                ('restaurant_rating', models.FloatField(blank=True, null=True)),
                ('restaurant_price_level', models.IntegerField(blank=True, null=True)),
                ('restaurant_lat', models.FloatField(blank=True, null=True)),
                ('restaurant_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'restaurant_place_id')},
            },
        ),
    ]
