# Generated by Django 5.2.6 on 2025-09-28 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_post_dining_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內容')),
                ('announcement_type', models.CharField(choices=[('system', '系統公告'), ('maintenance', '系統維護'), ('update', '功能更新'), ('promotion', '活動宣傳'), ('other', '其他')], default='system', max_length=15, verbose_name='公告類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置頂')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始日期')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束日期')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'verbose_name': '系統公告',
                'verbose_name_plural': '系統公告',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_registration_number', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=200)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('registration_document', models.FileField(upload_to='verification_documents')),
                ('additional_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unverified', '未驗證'), ('pending', '審核中'), ('verified', '已驗證'), ('rejected', '已拒絕')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', '評論'), ('reply', '回覆'), ('follow', '追蹤'), ('favorite', '收藏'), ('reaction', '表情符號'), ('system', '系統通知')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True)),
                ('favorite_foods', models.CharField(blank=True, help_text='請列出您喜愛的食物，用逗號分隔', max_length=200)),
                ('food_restrictions', models.CharField(blank=True, help_text='請列出您的飲食禁忌，用逗號分隔', max_length=200)),
                ('user_type', models.CharField(choices=[('general', '一般使用者'), ('business', '商家'), ('admin', '管理員')], default='general', max_length=10)),
                ('verification_status', models.CharField(choices=[('unverified', '未驗證'), ('pending', '審核中'), ('verified', '已驗證'), ('rejected', '已拒絕')], default='unverified', max_length=10)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.CharField(blank=True, max_length=200, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('post', '貼文'), ('comment', '評論'), ('user', '用戶'), ('other', '其他')], max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('resolved', '已解決'), ('rejected', '已拒絕')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.comment')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_foods', models.TextField(blank=True, help_text='用户偏好的食物，以逗號分隔')),
                ('food_restrictions', models.TextField(blank=True, help_text='飲食限制（如過敏、素食等）')),
                ('preferred_price_level', models.IntegerField(blank=True, help_text='偏好的價格等級(0-4)', null=True)),
                ('cuisine_preferences', models.TextField(blank=True, help_text='偏好的菜系，以逗號分隔')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_address', models.CharField(blank=True, max_length=300, null=True)),
                ('restaurant_image_url', models.URLField(blank=True, null=True)),
                ('restaurant_place_id', models.CharField(blank=True, max_length=300, null=True)),
                ('restaurant_rating', models.FloatField(blank=True, null=True)),
                ('restaurant_price_level', models.IntegerField(blank=True, null=True)),
                ('restaurant_lat', models.FloatField(blank=True, null=True)),
                ('restaurant_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'restaurant_place_id')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preference_type', models.CharField(help_text='偏好類型（口味/菜系/地區/禁忌）', max_length=20)),
                ('preference_value', models.CharField(help_text='偏好值（如：不辣/日式料理/台北市）', max_length=255)),
                ('score', models.FloatField(help_text='對該偏好的強度（+代表喜好，-代表排斥）')),
                ('source', models.CharField(help_text='來源（dialog/post/collection）', max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='對應該來源的id，例如貼文編號', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='記錄建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最後更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'preference_type'], name='user_userpr_user_id_a59683_idx'), models.Index(fields=['user', 'score'], name='user_userpr_user_id_9c9f37_idx')],
            },
        ),
    ]
