# Generated by Django 5.2.6 on 2025-09-20 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='聊天標題', max_length=255, verbose_name='聊天標題')),
                ('content', models.TextField(help_text='完整的聊天內容HTML', verbose_name='聊天內容（HTML）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '聊天歷史',
                'verbose_name_plural': '聊天歷史',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='訊息內容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='時間戳')),
                ('is_bot_response', models.BooleanField(default=False, verbose_name='是否為機器人回覆')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '訊息',
                'verbose_name_plural': '訊息',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='查詢內容')),
                ('response_text', models.TextField(verbose_name='回覆內容')),
                ('tools_used', models.CharField(blank=True, help_text='使用的工具，以逗號分隔', max_length=255, verbose_name='使用工具')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '查詢歷史',
                'verbose_name_plural': '查詢歷史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='食物名稱')),
                ('description', models.TextField(verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recommendation_images', verbose_name='圖片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '推薦結果',
                'verbose_name_plural': '推薦結果',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_foods', models.TextField(blank=True, help_text='用户偏好的食物，以逗號分隔', verbose_name='偏好食物')),
                ('food_restrictions', models.TextField(blank=True, help_text='飲食限制（如過敏、素食等）', verbose_name='飲食限制')),
                ('preferred_price_level', models.IntegerField(blank=True, help_text='偏好的價格等級(0-4)', null=True, verbose_name='偏好價格等級')),
                ('cuisine_preferences', models.TextField(blank=True, help_text='偏好的菜系，以逗號分隔', verbose_name='偏好菜系')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者偏好',
                'verbose_name_plural': '使用者偏好',
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='用戶對此地點的筆記', verbose_name='備註')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='儲存時間')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='restaurants.restaurant', verbose_name='餐廳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '已儲存地點',
                'verbose_name_plural': '已儲存地點',
                'unique_together': {('user', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('preference_type', models.CharField(help_text='偏好類型（口味/菜系/地區/禁忌）', max_length=20, verbose_name='偏好類型')),
                ('preference_value', models.CharField(help_text='偏好值（如：不辣/日式料理/台北市）', max_length=255, verbose_name='偏好值')),
                ('score', models.FloatField(help_text='對該偏好的強度（+代表喜好，-代表排斥）', verbose_name='偏好分數')),
                ('source', models.CharField(help_text='來源（dialog/post/collection）', max_length=20, verbose_name='來源')),
                ('source_id', models.IntegerField(blank=True, help_text='對應該來源的id，例如貼文編號', null=True, verbose_name='來源ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='記錄建立時間', verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最後更新時間', verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_details', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '偏好明細',
                'verbose_name_plural': '偏好明細',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'preference_type'], name='chat_userpr_user_id_613479_idx'), models.Index(fields=['user', 'score'], name='chat_userpr_user_id_6e01be_idx')],
            },
        ),
    ]
