# Generated by Django 4.2.20 on 2025-05-12 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_foods', models.TextField(blank=True, help_text='用户偏好的食物，以逗號分隔')),
                ('food_restrictions', models.TextField(blank=True, help_text='飲食限制（如過敏、素食等）')),
                ('preferred_price_level', models.IntegerField(blank=True, help_text='偏好的價格等級(0-4)', null=True)),
                ('cuisine_preferences', models.TextField(blank=True, help_text='偏好的菜系，以逗號分隔')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('tools_used', models.CharField(blank=True, help_text='使用的工具，以逗號分隔', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Query histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(help_text='Google Places API 地點ID', max_length=255)),
                ('place_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price_level', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='用戶對此地點的筆記')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'place_id')},
            },
        ),
    ]
