# Generated by Django 4.2.20 on 2025-05-17 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_userpreference_queryhistory_savedplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferenceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preference_type', models.CharField(help_text='偏好類型（口味/菜系/地區/禁忌）', max_length=20)),
                ('preference_value', models.CharField(help_text='偏好值（如：不辣/日式料理/台北市）', max_length=255)),
                ('score', models.FloatField(help_text='對該偏好的強度（+代表喜好，-代表排斥）')),
                ('source', models.CharField(help_text='來源（dialog/post/collection）', max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='對應該來源的id，例如貼文編號', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='記錄建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最後更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'preference_type'], name='chat_userpr_user_id_613479_idx'), models.Index(fields=['user', 'score'], name='chat_userpr_user_id_6e01be_idx')],
            },
        ),
    ]
