# Generated by Django 5.2.6 on 2025-09-29 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='current_open_now',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='editorial_summary',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='intl_phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='language',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='open_until',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='primary_source',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='raw_json',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='reopen_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='utc_offset_minutes',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='language',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='profile_photo_url',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='raw_json',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='source',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='time_unix',
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='category_scores',
            field=models.JSONField(blank=True, null=True, verbose_name='類別及細項評分'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(help_text='來源唯一識別碼', max_length=300, unique=True, verbose_name='Place ID'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='評論時間'),
        ),
        migrations.CreateModel(
            name='RestaurantIndicatorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(help_text='指標類型（食物/服務/環境/價錢等）', max_length=20, verbose_name='指標類型')),
                ('score', models.FloatField(help_text='該指標的分數（如情感分數）', verbose_name='分數')),
                ('source', models.CharField(help_text='來源（post/review等）', max_length=20, verbose_name='來源')),
                ('source_id', models.IntegerField(blank=True, help_text='來源的ID，例如貼文ID', null=True, verbose_name='來源ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_details', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '餐廳指標細項',
                'verbose_name_plural': '餐廳指標細項',
            },
        ),
        migrations.CreateModel(
            name='RestaurantIndicatorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(max_length=20, verbose_name='指標類型')),
                ('total_score', models.FloatField(verbose_name='總分數')),
                ('count', models.IntegerField(default=0, verbose_name='統計次數')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_summaries', to='restaurants.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '餐廳指標總表',
                'verbose_name_plural': '餐廳指標總表',
            },
        ),
        migrations.DeleteModel(
            name='RestaurantSpecialHour',
        ),
        migrations.AddIndex(
            model_name='restaurantindicatordetail',
            index=models.Index(fields=['restaurant', 'indicator_type'], name='restaurants_restaur_a518fb_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantindicatorsummary',
            index=models.Index(fields=['restaurant', 'indicator_type'], name='restaurants_restaur_ae7e3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantindicatorsummary',
            unique_together={('restaurant', 'indicator_type')},
        ),
    ]
